### ISSUE TITLE
Number of ID issue

### ISSUE THREAD

**Issue by hideyuki-oiso** [Ruframapi/HABLA#1]
Hello.
Thanks for the great repository and dataset release.

I have found a flaw in the dataset you publish on google drive.
The total number of datasets should be 22816 for bonafide and 58000 for spoofed for a total of 80816.
But the total number of rows in the public datasets `scp/train.lst`, `scp/val.lst` and `scp/test.lst` is 80817.
I found a typo in `scp/test.lst` on line 22283 for the string 'protocol.txt'. I believe that this ID is not contained within `protocol.txt` and is a line that should be deleted.
We believe that this bug probably has no effect on the results, but we would appreciate a fix.

Sincerely yours

**Comment by ghost** [comment]
Hi, problem solved, thank you very much for the advisor!
